server:
  port: 8080

spring:
  datasource:
    username: root
    password: Qwer1234
    url: jdbc:mysql://localhost:3306/search_engine?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      ddl-import_files: import.sql

indexing-settings:
  sites:
    - url: https://sadsk.ru
      name: sad

#connect:
#  user-agent: